services:
    
    db:
        image: postgres:16
        restart: always
        env_file:
            - .env
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - kisy-network
    web:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - .:/app
        ports:
            - "8001:8000"
        networks:
            - kisy-network
    minio:
        image: minio/minio:latest
        container_name: minio
        ports:
            - "9000:9000"
            - "9001:9001"
        env_file:
            - .env
        volumes:
            - minio_data:/data
        networks:
            - kisy-network
        command: server /data --console-address ":9001"
networks:
    kisy-network:
volumes:
    pgdata:
