services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        volumes:
            - .:/app
        ports:
            - "8001:8000"
        networks:
            - kisy-network
        restart: unless-stopped
networks:
    kisy-network: