services:
    db:
        image: postgres:16
        restart: always
        env_file:
            - .env
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - kisy-network
    web:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - .:/app
        ports:
            - "8001:8000"
        networks:
            - kisy-network
networks:
    kisy-network:
volumes:
    pgdata: