"""empty message

Revision ID: 47b3f9858033
Revises: 5e9064d5181c
Create Date: 2025-10-16 23:32:49.264437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47b3f9858033'
down_revision: Union[str, Sequence[str], None] = '5e9064d5181c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods_variations', sa.Column('remaining_stock', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods_variations', 'remaining_stock')
    # ### end Alembic commands ###
