"""empty message

Revision ID: 5e9064d5181c
Revises: e2d9a931573e
Create Date: 2025-10-16 22:26:22.843138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e9064d5181c'
down_revision: Union[str, Sequence[str], None] = 'e2d9a931573e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('show_in_catalog', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'show_in_catalog')
    # ### end Alembic commands ###
