"""empty message

Revision ID: e2d9a931573e
Revises: 79b32c57d5e7
Create Date: 2025-09-27 15:14:21.650065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2d9a931573e'
down_revision: Union[str, Sequence[str], None] = '79b32c57d5e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('good_variation_price_good_variation_id_fkey'), 'good_variation_price', type_='foreignkey')
    op.create_foreign_key(None, 'good_variation_price', 'goods_variations', ['good_variation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'good_variation_price', type_='foreignkey')
    op.create_foreign_key(op.f('good_variation_price_good_variation_id_fkey'), 'good_variation_price', 'goods_variations', ['good_variation_id'], ['id'])
    # ### end Alembic commands ###
